#!/usr/bin/env node

var compress = require('./lib/compress').compress;

var out = compress(
  "div, x { color: red }" +
  "h1 {color: #ff0000 '1px'; display: none !important;margin: 0px;background:green;}" +
  ".fonts { text-shadow: 0    0    20px; }" +
  ".foobar { color: red }" +
  "@media screen { foo { color: red } bar { color: blue } }" +
  "@keyframes foo { 100% { color: red } }"
);
console.log(out);
